var PUBLIC_READ_ACTIONS = Object.freeze([
  'health','getSettings','getSites','getBuildings','getUtilities','getMeters','getMeterReadings','getConsumption',
  'getHistoricalConsumption','getAnomalies','getCases','getCaseDetails','getEvidence','getCorrectiveActions','getDashboard',
  'getPortfolioTree','getConsumptionIntelligence','getHistoricalAnalysis','getComparisonData','getOpportunities','getTodaySummary',
  'getMonthlyChecklist','getDataQualityIssues'
]);
var PROTECTED_WRITE_ACTIONS = Object.freeze([
  'createMeterReading','updateMeterReading','createInvestigationInput','updateInvestigationInput','createEvidence',
  'updateEvidenceStatus','createCorrectiveAction','updateCorrectiveAction','updateCase','confirmRootCause','closeCase',
  'updateAnomaly','createInvestigationCase'
]);
function routeAccess_(method, action) {
  var verb=String(method||'').toUpperCase();
  if(verb==='GET'&&PUBLIC_READ_ACTIONS.indexOf(action)>=0)return {public:true,protected:false};
  if(verb==='POST'&&PROTECTED_WRITE_ACTIONS.indexOf(action)>=0)return {public:false,protected:true};
  if((verb==='GET'&&PROTECTED_WRITE_ACTIONS.indexOf(action)>=0)||(verb==='POST'&&PUBLIC_READ_ACTIONS.indexOf(action)>=0))throw apiError_('METHOD_NOT_ALLOWED','This action cannot be used with '+verb+'.',{method:verb,action:action});
  throw apiError_('UNKNOWN_ACTION','The requested API action is not supported.',{method:verb,action:action});
}

function readAction_(action, params) {
  var routes = {
    getSettings: function() { return readAll_('settings'); },
    getDataQualityIssues: function() { return filterRecords_(readAll_('quality'), params, {siteId:'Site_ID',buildingId:'Building_ID',utilityId:'Utility_ID',meterId:'Meter_ID',status:'Status'}); },
    getSites: function() { return filterRecords_(readAll_('sites'), params, SCHEMA.sites); },
    getBuildings: function() { return filterRecords_(readAll_('buildings'), params, SCHEMA.buildings); },
    getUtilities: function() { return filterRecords_(readAll_('utilities'), params, SCHEMA.utilities); },
    getMeters: function() { return filterRecords_(readAll_('meters'), params, SCHEMA.meters); },
    getMeterReadings: function() { return dateRangeFilter_(filterRecords_(readAll_('readings'), params, SCHEMA.readings), 'Reading_Date', params.dateFrom, params.dateTo); },
    getConsumption: function() { return dateRangeFilter_(filterRecords_(readAll_('consumption'), params, SCHEMA.consumption), 'Period_From', params.periodFrom, params.periodTo); },
    getHistoricalConsumption: function() { return yearRangeFilter_(filterRecords_(readAll_('historical'), params, { site:'Site', building:'Building', utility:'Utility' }), params.yearFrom, params.yearTo); },
    getAnomalies: function() { return filterRecords_(readAll_('anomalies'), params, SCHEMA.anomalies); },
    getCases: function() { return filterRecords_(readAll_('cases'), params, SCHEMA.cases); },
    getEvidence: function() { return filterRecords_(readAll_('evidence'), params, SCHEMA.evidence); },
    getCorrectiveActions: function() { var rows = filterRecords_(readAll_('actions'), params, SCHEMA.actions); return params.overdue === 'true' ? rows.filter(isOverdue_) : rows; },
    getDashboard: function() { return calculateDashboard_(); },
    getPortfolioTree: function() { return portfolioTree_(); },
    getCaseDetails: function() { return caseDetails_(params.caseId); },
    getConsumptionIntelligence: function() { return getConsumptionIntelligence_(params); },
    getHistoricalAnalysis: function() { return getHistoricalAnalysis_(params); },
    getComparisonData: function() { return getComparisonData_(params); },
    getOpportunities: function() { return getOpportunities_(params); },
    getTodaySummary: function() { return getTodaySummary_(params); },
    getMonthlyChecklist: function() { return getMonthlyChecklist_(); }
  };
  if (!routes[action]) throw apiError_('UNKNOWN_ACTION', 'Unknown read action.', { action: action });
  return routes[action]();
}
function dateRangeFilter_(rows, header, from, to) { return rows.filter(function(row) { var date = new Date(row[header]); return (!from || date >= new Date(from)) && (!to || date <= new Date(to)); }); }
function yearRangeFilter_(rows, from, to) { return rows.filter(function(row) { var year = Number(row.Year || String(row.Period || '').slice(0,4)); return (!from || year >= Number(from)) && (!to || year <= Number(to)); }); }
function isOverdue_(row) { return row.Target_Date && new Date(row.Target_Date) < new Date() && ['completed','verified','cancelled'].indexOf(String(row.Status).toLowerCase()) < 0; }
function caseDetails_(caseId) { requireFields_({ caseId: caseId }, ['caseId']); var item = findById_('cases', caseId); if (!item) throw apiError_('NOT_FOUND', 'Investigation case was not found.', { caseId: caseId }); var meter = item.Meter_ID ? findById_('meters', item.Meter_ID) : null; return { case: item, meter: meter, site: item.Site_ID ? findById_('sites', item.Site_ID) : null, building: meter && meter.Building_ID ? findById_('buildings', meter.Building_ID) : null, utility: item.Utility_ID ? findById_('utilities', item.Utility_ID) : null, investigationInputs: filterRecords_(readAll_('inputs'), { Case_ID: caseId }, {}), evidence: filterRecords_(readAll_('evidence'), { caseId: caseId }, SCHEMA.evidence), correctiveActions: filterRecords_(readAll_('actions'), { caseId: caseId }, SCHEMA.actions), relatedAnomaly: item.Anomaly_ID ? findById_('anomalies', item.Anomaly_ID) : null, consumptionHistory: meter ? filterRecords_(readAll_('consumption'), { meterId: meter.Meter_ID }, SCHEMA.consumption) : [] }; }
function calculateDashboard_() { var sites=readAll_('sites').filter(active_), buildings=readAll_('buildings').filter(active_), meters=readAll_('meters').filter(active_), readings=readAll_('readings'), cases=readAll_('cases'), anomalies=readAll_('anomalies'), quality=readAll_('quality'), actions=readAll_('actions'); var moneyAtRisk=null,potentialSavings=null; var valued=anomalies.filter(function(a){return a.Tariff!==null&&a.Tariff!==undefined&&a.Excess_Consumption!==null&&a.Excess_Consumption!==undefined;}); if(valued.length) moneyAtRisk=valued.reduce(function(sum,a){return sum+Number(a.Tariff)*Number(a.Excess_Consumption);},0); var supported=actions.filter(function(a){return a.Expected_Saving!==null&&a.Expected_Saving!==undefined;}); if(supported.length) potentialSavings=supported.reduce(function(sum,a){return sum+Number(a.Expected_Saving);},0); return { liveSites:sites.length, buildings:buildings.length, mappedMeters:meters.length, pendingVerificationReadings:readings.filter(function(r){return String(r.Verification_Status).toLowerCase()!=='verified';}).length, openInvestigations:cases.filter(function(c){return !['closed','cancelled'].includes(String(c.Status).toLowerCase());}).length, criticalAnomalies:anomalies.filter(function(a){return String(a.Severity).toLowerCase()==='critical';}).length, highAnomalies:anomalies.filter(function(a){return String(a.Severity).toLowerCase()==='high';}).length, dataQualityIssues:quality.filter(active_).length, correctiveActionsOverdue:actions.filter(isOverdue_).length, moneyAtRisk:moneyAtRisk, potentialSavings:potentialSavings }; }
function active_(record){return ['inactive','deleted','cancelled','closed'].indexOf(String(record.Status||'active').toLowerCase())<0;}
function portfolioTree_(){var sites=readAll_('sites'),buildings=readAll_('buildings'),utilities=readAll_('utilities'),meters=readAll_('meters');return {name:'Portfolio',sites:sites.map(function(site){return {site:site,buildings:buildings.filter(function(b){return String(b.Site_ID)===String(site.Site_ID);}).map(function(building){return {building:building,utilities:utilities.map(function(utility){return {utility:utility,meters:meters.filter(function(m){return String(m.Site_ID)===String(site.Site_ID)&&String(m.Building_ID)===String(building.Building_ID)&&String(m.Utility_ID)===String(utility.Utility_ID);})};}).filter(function(node){return node.meters.length;})};})};})};}
function writeAction_(action, body) {
  var routes = {
    createMeterReading: function(){requireFields_(body,['meterId','readingDate','readingValue','enteredBy']);assertForeignKey_('meters',body.meterId,'meterId');assertDate_(body.readingDate,'readingDate');var value=assertNumeric_(body.readingValue,'readingValue',true);assertNoDuplicateReading_(body.meterId,body.readingDate,body.readingTime);assertReadingContinuity_(body.meterId,body.readingDate,value,body.meterReset);var record={Reading_ID:uniqueId_('RDG'),Meter_ID:body.meterId,Reading_Date:body.readingDate,Reading_Time:body.readingTime||'',Reading_Value:value,Entered_By:body.enteredBy,Photo_Link:body.photoLink||'',Remarks:body.remarks||'',Meter_Reset:Boolean(body.meterReset),Estimated_Reading:Boolean(body.estimatedReading),Verification_Status:'Pending verification'};return createAudited_('readings',record,'MeterReading',body);},
    updateMeterReading: function(){requireFields_(body,['readingId','enteredBy']);var old=findById_('readings',body.readingId);if(!old)throw apiError_('NOT_FOUND','Meter reading was not found.',{readingId:body.readingId});var meterId=body.meterId||old.Meter_ID,date=body.readingDate||old.Reading_Date,time=body.readingTime===undefined?old.Reading_Time:body.readingTime,value=body.readingValue===undefined?old.Reading_Value:assertNumeric_(body.readingValue,'readingValue',true);assertNoDuplicateReading_(meterId,date,time,body.readingId);assertReadingContinuity_(meterId,date,value,body.meterReset);return updateAudited_('readings',body.readingId,mapPayload_(body,{meterId:'Meter_ID',readingDate:'Reading_Date',readingTime:'Reading_Time',readingValue:'Reading_Value',photoLink:'Photo_Link',remarks:'Remarks',meterReset:'Meter_Reset',estimatedReading:'Estimated_Reading',verificationStatus:'Verification_Status'}),'MeterReading',body);},
    createInvestigationInput:function(){requireFields_(body,['caseId','questionId','answer','enteredBy']);assertForeignKey_('cases',body.caseId,'caseId');return createAudited_('inputs',{Input_ID:uniqueId_('INP'),Case_ID:body.caseId,Question_ID:body.questionId,Answer:body.answer,Status:body.status||'Answered',Mandatory:Boolean(body.mandatory),Entered_By:body.enteredBy,Entered_At:new Date(),Technical_Notes:body.technicalNotes||''},'InvestigationInput',body);},
    updateInvestigationInput:function(){requireFields_(body,['inputId','enteredBy']);return updateAudited_('inputs',body.inputId,mapPayload_(body,{answer:'Answer',status:'Status',technicalNotes:'Technical_Notes',verificationStatus:'Verification_Status',assignedTo:'Assigned_To',dueDate:'Due_Date'}),'InvestigationInput',body);},
    createEvidence:function(){requireFields_(body,['caseId','fileLink','fileName','uploader','evidenceType']);assertForeignKey_('cases',body.caseId,'caseId');if(!/^https:\/\//i.test(body.fileLink))throw apiError_('VALIDATION_ERROR','Evidence must use an HTTPS file link.',{field:'fileLink'});return createAudited_('evidence',{Evidence_ID:uniqueId_('EVD'),Case_ID:body.caseId,Question_ID:body.questionId||'',File_Link:body.fileLink,File_Name:body.fileName,Uploaded_By:body.uploader,Evidence_Type:body.evidenceType,Verification_Status:body.verificationStatus||'Pending verification',Uploaded_At:new Date(),Remarks:body.remarks||''},'Evidence',body);},
    updateEvidenceStatus:function(){requireFields_(body,['evidenceId','verificationStatus','updatedBy']);assertAllowed_(body.verificationStatus,['Pending verification','Verified','Needs recheck','Rejected'],'verificationStatus');return updateAudited_('evidence',body.evidenceId,{Verification_Status:body.verificationStatus,Verified_By:body.updatedBy,Verified_At:new Date()},'Evidence',body);},
    createCorrectiveAction:function(){requireFields_(body,['caseId','description','assignedTo','status','enteredBy']);assertForeignKey_('cases',body.caseId,'caseId');return createAudited_('actions',{Action_ID:uniqueId_('ACT'),Case_ID:body.caseId,Description:body.description,Root_Cause:body.rootCause||'',Assigned_To:body.assignedTo,Priority:body.priority||'Medium',Target_Date:body.targetDate||'',Status:body.status,Expected_Saving:body.expectedSaving===undefined?'':assertNumeric_(body.expectedSaving,'expectedSaving',true),Verification_Method:body.verificationMethod||''},'CorrectiveAction',body);},
    updateCorrectiveAction:function(){requireFields_(body,['actionId','updatedBy']);return updateAudited_('actions',body.actionId,mapPayload_(body,{description:'Description',assignedTo:'Assigned_To',priority:'Priority',targetDate:'Target_Date',status:'Status',expectedSaving:'Expected_Saving',verificationMethod:'Verification_Method',closureRemarks:'Closure_Remarks'}),'CorrectiveAction',body);},
    updateCase:function(){requireFields_(body,['caseId','updatedBy']);return updateAudited_('cases',body.caseId,mapPayload_(body,{status:'Status',severity:'Severity',assignedTo:'Assigned_To',notes:'Notes'}),'InvestigationCase',body);},
    confirmRootCause:function(){requireFields_(body,['caseId','rootCause','confirmedBy']);var missing=rootCauseGates_(body.caseId);if(missing.length)throw apiError_('ROOT_CAUSE_LOCKED','Root cause cannot be confirmed until all gates are complete.',{missingGates:missing});return updateAudited_('cases',body.caseId,{Confirmed_Root_Cause:body.rootCause,Root_Cause_Status:'Confirmed',Root_Cause_Confirmed_By:body.confirmedBy,Root_Cause_Confirmed_At:new Date()},'InvestigationCase',body);},
    createInvestigationCase:function(){requireFields_(body,['anomalyId','createdBy']);var anomaly=findById_('anomalies',body.anomalyId);if(!anomaly)throw apiError_('NOT_FOUND','Alert record was not found.',{anomalyId:body.anomalyId});if(anomaly.Case_ID)throw apiError_('DUPLICATE_CASE','An investigation already exists for this alert.',{caseId:anomaly.Case_ID});var record={Case_ID:uniqueId_('CASE'),Case_Title:body.title||anomaly.Title||'Utility alert investigation',Anomaly_ID:body.anomalyId,Meter_ID:anomaly.Meter_ID||'',Site_ID:anomaly.Site_ID||'',Utility_ID:anomaly.Utility_ID||'',Severity:anomaly.Severity||'Review',Status:'Data Collection',Root_Cause_Status:'Not Assessed',Assigned_To:body.assignedTo||''};var created=createAudited_('cases',record,'InvestigationCase',{enteredBy:body.createdBy,auditRemarks:'Created explicitly from reviewed alert'});updateAudited_('anomalies',body.anomalyId,{Case_ID:record.Case_ID,Status:'Under Investigation'},'Anomaly',{updatedBy:body.createdBy,auditRemarks:'Linked to explicitly created investigation'});return created;},
    updateAnomaly:function(){requireFields_(body,['anomalyId','status','updatedBy']);return updateAudited_('anomalies',body.anomalyId,mapPayload_(body,{status:'Status',reason:'Explanation',assignedTo:'Assigned_To',remarks:'Remarks'}),'Anomaly',body);},
    closeCase:function(){requireFields_(body,['caseId','closureApprover']);var missing=closureGates_(body.caseId,body.closureApprover);if(missing.length)throw apiError_('CASE_CLOSURE_LOCKED','Case closure requirements are incomplete.',{missingGates:missing});return updateAudited_('cases',body.caseId,{Status:'Closed',Closure_Approver:body.closureApprover,Closed_At:new Date(),Closure_Remarks:body.remarks||''},'InvestigationCase',body);}
  };
  if(!routes[action])throw apiError_('UNKNOWN_ACTION','Unknown write action.',{action:action});
  return withWriteLock_(routes[action]);
}
function mapPayload_(body,mapping){var patch={};Object.keys(mapping).forEach(function(key){if(body[key]!==undefined)patch[mapping[key]]=body[key];});return patch;}
function createAudited_(key,record,entityType,body){assertUniqueId_(key,record[CONFIG.IDS[key]]);appendRecord_(key,record);var audit=appendAudit_({user:body.enteredBy||body.uploader||body.updatedBy||body.confirmedBy||body.closureApprover,action:'CREATE',entityType:entityType,entityId:record[CONFIG.IDS[key]],newValue:record,remarks:body.auditRemarks});return {record:record,auditLogId:audit.Log_ID};}
function updateAudited_(key,id,patch,entityType,body){var result=updateRecord_(key,id,patch);var audit=appendAudit_({user:body.enteredBy||body.updatedBy||body.confirmedBy||body.closureApprover,action:'UPDATE',entityType:entityType,entityId:id,oldValue:result.oldValue,newValue:result.newValue,remarks:body.auditRemarks});return {record:result.newValue,auditLogId:audit.Log_ID};}
