function spreadsheet_() { return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID); }
function sheet_(key) { var name = CONFIG.SHEETS[key]; var sheet = spreadsheet_().getSheetByName(name); if (!sheet) throw apiError_('SHEET_NOT_FOUND', 'Required sheet is unavailable: ' + name, { sheet: name }); return sheet; }
function normalizeCell_(value) { if (value instanceof Date) return Utilities.formatDate(value, CONFIG.TIMEZONE, "yyyy-MM-dd'T'HH:mm:ssXXX"); return value === '' ? null : value; }
function rowsToObjects_(values) { if (!values || values.length < 2) return []; var headers = values[0].map(String); return values.slice(1).filter(function(row) { return row.some(function(value) { return value !== ''; }); }).map(function(row) { var record = {}; headers.forEach(function(header, index) { record[header] = normalizeCell_(row[index]); }); return record; }); }
function readAll_(key) { var cache=CacheService.getScriptCache(),cacheKey='M4:'+CONFIG.DATA_VERSION+':'+key,cached=cache.get(cacheKey);if(cached){try{return JSON.parse(cached);}catch(ignore){}}var values=sheet_(key).getDataRange().getValues(),records=rowsToObjects_(values),json=JSON.stringify(records);if(json.length<90000)cache.put(cacheKey,json,120);return records;}
function invalidateReadCache_(key){CacheService.getScriptCache().remove('M4:'+CONFIG.DATA_VERSION+':'+key);}
function recordValue_(record, header) { return record[header] === undefined ? null : record[header]; }
function filterRecords_(records, filters, mapping) { return records.filter(function(record) { return Object.keys(filters || {}).every(function(key) { var expected = filters[key]; if (expected === undefined || expected === null || expected === '') return true; var header = mapping[key] || key; if (['action','token','apiToken'].indexOf(key) >= 0) return true; if (!mapping[key] && !Object.prototype.hasOwnProperty.call(record, header)) return true; return String(recordValue_(record, header)).toLowerCase() === String(expected).toLowerCase(); }); }); }
function findById_(key, id) { var header = CONFIG.IDS[key]; if (!header) throw apiError_('SCHEMA_ERROR', 'No ID mapping exists for ' + key, {}); var records = readAll_(key); return records.filter(function(record) { return String(record[header]) === String(id); })[0] || null; }
function findRowById_(key, id) { var target = sheet_(key); var values = target.getDataRange().getValues(); var headers = values[0].map(String); var idHeader = CONFIG.IDS[key]; var index = headers.indexOf(idHeader); if (index < 0) throw apiError_('SCHEMA_ERROR', 'ID column is missing: ' + idHeader, { sheet: CONFIG.SHEETS[key] }); for (var row = 1; row < values.length; row++) if (String(values[row][index]) === String(id)) return { sheet: target, row: row + 1, headers: headers, record: rowsToObjects_([headers, values[row]])[0] }; return null; }
function appendRecord_(key, record) { var target = sheet_(key); var headers = target.getRange(1, 1, 1, target.getLastColumn()).getValues()[0].map(String); var unknown = Object.keys(record).filter(function(field) { return headers.indexOf(field) < 0; }); if (unknown.length) throw apiError_('SCHEMA_ERROR', 'Payload includes columns not found in the sheet.', { columns: unknown, sheet: CONFIG.SHEETS[key] }); target.appendRow(headers.map(function(header) { return record[header] === undefined ? '' : record[header]; })); invalidateReadCache_(key); return record; }
function updateRecord_(key, id, patch) { var found = findRowById_(key, id); if (!found) throw apiError_('NOT_FOUND', 'Record was not found.', { entity: key, id: id }); var unknown = Object.keys(patch).filter(function(field) { return found.headers.indexOf(field) < 0; }); if (unknown.length) throw apiError_('SCHEMA_ERROR', 'Payload includes columns not found in the sheet.', { columns: unknown }); var updated = {}; found.headers.forEach(function(header, index) { updated[header] = patch[header] === undefined ? found.record[header] : patch[header]; found.sheet.getRange(found.row, index + 1).setValue(updated[header] === null ? '' : updated[header]); }); invalidateReadCache_(key); return { oldValue: found.record, newValue: updated };
}
function uniqueId_(prefix) { return prefix + '-' + Utilities.formatDate(new Date(), CONFIG.TIMEZONE, 'yyyyMMddHHmmss') + '-' + Utilities.getUuid().slice(0, 8).toUpperCase(); }
