function requireFields_(payload, fields) { var missing = fields.filter(function(field) { return payload[field] === undefined || payload[field] === null || String(payload[field]).trim() === ''; }); if (missing.length) throw apiError_('VALIDATION_ERROR', 'Required fields are missing.', { missing: missing }); }
function assertId_(value, field) { if (!/^[A-Za-z0-9][A-Za-z0-9_-]{2,79}$/.test(String(value || ''))) throw apiError_('VALIDATION_ERROR', field + ' is invalid.', { field: field }); }
function assertDate_(value, field) { var date = new Date(value); if (!value || isNaN(date.getTime())) throw apiError_('VALIDATION_ERROR', field + ' must be a valid date.', { field: field }); return date; }
function assertNumeric_(value, field, allowZero) { if (value === '' || value === null || value === undefined || !isFinite(Number(value))) throw apiError_('VALIDATION_ERROR', field + ' must be numeric.', { field: field }); if (Number(value) < 0 || (!allowZero && Number(value) === 0)) throw apiError_('VALIDATION_ERROR', field + ' must be ' + (allowZero ? 'zero or greater.' : 'positive.'), { field: field }); return Number(value); }
function assertAllowed_(value, allowed, field) { if (allowed.indexOf(String(value)) < 0) throw apiError_('VALIDATION_ERROR', field + ' is not allowed.', { field: field, allowed: allowed }); }
function assertForeignKey_(key, id, field) { if (!findById_(key, id)) throw apiError_('VALIDATION_ERROR', field + ' does not reference an existing record.', { field: field, value: id }); }
function assertUniqueId_(key, id) { if (findById_(key, id)) throw apiError_('DUPLICATE_ID', 'The record ID already exists.', { entity: key, id: id }); }
function assertPeriod_(from, to) { if (assertDate_(from, 'periodFrom') > assertDate_(to, 'periodTo')) throw apiError_('VALIDATION_ERROR', 'Period start cannot be after period end.', {}); }
function assertReadingContinuity_(meterId, readingDate, readingValue, meterReset) { var rows = filterRecords_(readAll_('readings'), { meterId: meterId }, SCHEMA.readings).filter(function(row) { return new Date(row[SCHEMA.readings.date]) < new Date(readingDate); }).sort(function(a,b) { return new Date(b[SCHEMA.readings.date]) - new Date(a[SCHEMA.readings.date]); }); if (rows.length && Number(readingValue) < Number(rows[0][SCHEMA.readings.value]) && !meterReset) throw apiError_('CONTINUITY_ERROR', 'Reading is below the previous reading. Record a verified meter reset or correct the value.', { previousReading: rows[0] }); }
function assertNoDuplicateReading_(meterId, date, time, excludeId) { var duplicate = readAll_('readings').filter(function(row) { return String(row.Meter_ID) === String(meterId) && String(row.Reading_Date).slice(0,10) === String(date).slice(0,10) && String(row.Reading_Time || '') === String(time || '') && String(row.Reading_ID) !== String(excludeId || ''); })[0]; if (duplicate) throw apiError_('DUPLICATE_READING', 'A reading already exists for this meter, date, and time. Use updateMeterReading explicitly.', { readingId: duplicate.Reading_ID }); }
function rootCauseGates_(caseId) { var missing = [], caseRecord = findById_('cases', caseId); if (!caseRecord) return ['case exists']; var evidence = filterRecords_(readAll_('evidence'), { caseId: caseId }, SCHEMA.evidence); if (!evidence.some(function(row) { return String(row.Verification_Status).toLowerCase() === 'verified'; })) missing.push('verified evidence'); var inputs = filterRecords_(readAll_('inputs'), { Case_ID: caseId }, {}); if (inputs.some(function(row) { return String(row.Mandatory).toLowerCase() === 'yes' && !['answered','verified','not applicable'].includes(String(row.Status).toLowerCase()); })) missing.push('mandatory investigation inputs'); var meter = findById_('meters', caseRecord.Meter_ID); if (meter && String(meter.Meter_Type || '').toLowerCase().indexOf('ct') >= 0 && (!meter.CT_Ratio || !meter.Multiplier || String(meter.Verification_Status || '').toLowerCase() !== 'verified')) missing.push('verified CT ratio and multiplier'); var readings = filterRecords_(readAll_('readings'), { meterId: caseRecord.Meter_ID }, SCHEMA.readings); if (readings.length < 2 || readings.some(function(row) { return String(row.Verification_Status).toLowerCase() !== 'verified'; })) missing.push('required verified meter readings'); var actions = filterRecords_(readAll_('actions'), { caseId: caseId }, SCHEMA.actions); if (!actions.some(function(row) { return row.Assigned_To; })) missing.push('corrective action with assigned owner'); return missing; }
function closureGates_(caseId, approver) { var missing = [], record = findById_('cases', caseId); if (!record || !record.Confirmed_Root_Cause) missing.push('confirmed root cause'); var actions = filterRecords_(readAll_('actions'), { caseId: caseId }, SCHEMA.actions); if (!actions.some(function(row) { return ['completed','verified'].includes(String(row.Status).toLowerCase()); })) missing.push('completed corrective action'); var inputs = filterRecords_(readAll_('inputs'), { Case_ID: caseId }, {}); if (!inputs.some(function(row) { return String(row.Stage || '').toLowerCase().indexOf('verification') >= 0 && ['answered','verified'].includes(String(row.Status).toLowerCase()); })) missing.push('post-action verification'); if (!approver) missing.push('closure approver'); return missing; }
