const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const root=path.join(__dirname,'..','google-apps-script');
const sandbox={console,Date,JSON,Object,Array,String,Number,Boolean,Math,Error,isFinite,isNaN,Utilities:{getUuid:()=> 'uuid-1',formatDate:()=> '2026-08-03T12:00:00+04:00'},CacheService:{getScriptCache:()=>({get:()=>null,put:()=>{},remove:()=>{}})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this}})}};vm.createContext(sandbox);for(const file of ['Config.gs','ApiResponses.gs','SheetsRepository.gs','Validation.gs','AuditLog.gs','Intelligence.gs','Router.gs'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),sandbox,{filename:file});
const success=sandbox.responsePayload_(true,{ok:true},null,'REQ-1');assert.deepEqual(JSON.parse(JSON.stringify(success)),{success:true,data:{ok:true},error:null,meta:{apiVersion:'v1',timestamp:'2026-08-03T12:00:00+04:00',requestId:'REQ-1'}});const failure=sandbox.responsePayload_(false,null,{code:'X',message:'bad'},'REQ-2');assert.equal(failure.success,false);assert.equal(failure.data,null);
const rows=sandbox.rowsToObjects_([['Site_ID','Site_Name','Blank'],['SITE-EYP','Etihad Plaza','']]);assert.deepEqual(JSON.parse(JSON.stringify(rows)),[{Site_ID:'SITE-EYP',Site_Name:'Etihad Plaza',Blank:null}]);
assert.throws(()=>sandbox.requireFields_({meterId:'x'},['meterId','readingDate']),/Required fields/);assert.throws(()=>sandbox.assertNumeric_(-1,'readingValue',true),/zero or greater/);assert.throws(()=>sandbox.assertDate_('bad','readingDate'),/valid date/);
sandbox.readAll_=()=>[{Meter_ID:'M1',Reading_Date:'2026-07-01',Reading_Time:'10:00',Reading_ID:'R1'}];assert.throws(()=>sandbox.assertNoDuplicateReading_('M1','2026-07-01','10:00'),/already exists/);
let auditRecord=null;sandbox.appendRecord_=(key,record)=>{assert.equal(key,'audit');auditRecord=record};const audit=sandbox.appendAudit_({user:'Tester',action:'UPDATE',entityType:'MeterReading',entityId:'R1',oldValue:{a:1},newValue:{a:2}});assert.equal(auditRecord.Entity_ID,'R1');assert.equal(audit.Log_ID.startsWith('LOG-'),true);
const data={sites:[{Site_ID:'S',Status:'Active'}],buildings:[],meters:[{Meter_ID:'M',Status:'Active'}],readings:[{Verification_Status:'Pending verification'}],cases:[{Status:'Data Collection'}],anomalies:[{Severity:'Critical',Tariff:null}],quality:[],actions:[]};sandbox.readAll_=key=>data[key]||[];const dash=sandbox.calculateDashboard_();assert.equal(dash.liveSites,1);assert.equal(dash.moneyAtRisk,null);assert.equal(dash.criticalAnomalies,1);
sandbox.findById_=()=>null;assert.deepEqual(JSON.parse(JSON.stringify(sandbox.rootCauseGates_('missing'))),['case exists']);sandbox.findById_=()=>({});sandbox.filterRecords_=()=>[];sandbox.readAll_=()=>[];assert.equal(sandbox.closureGates_('C','').includes('closure approver'),true);
console.log('Apps Script response, repository conversion, validation, duplicate, audit, gates, and KPI tests passed');

const negative=sandbox.classifyConsumption_({current:-275,qualityIssue:false,zeroConfirmed:false,reductionVerified:false,validComparisons:1});assert.equal(negative.classification,'Data issue');const reduction=sandbox.classifyConsumption_({current:70,percentChange:-30,sameMonthAverage:90,normalMin:60,normalMax:110,qualityIssue:false,zeroConfirmed:false,reductionVerified:false,validComparisons:3});assert.equal(reduction.classification,'Watch');assert.match(reduction.explanation,/not confirmed/i);const seasonal=sandbox.classifyConsumption_({current:110,percentChange:10,sameMonthAverage:105,normalMin:90,normalMax:120,qualityIssue:false,zeroConfirmed:false,reductionVerified:false,validComparisons:3});assert.equal(seasonal.classification,'Explained variation');
const originalIntel=sandbox.getConsumptionIntelligence_;sandbox.getConsumptionIntelligence_=()=>({items:[{unit:'kWh',record:{Meter_ID:'E',Utility_ID:'ELEC'}},{unit:'m3',record:{Meter_ID:'W',Utility_ID:'WATER'}}]});assert.throws(()=>sandbox.getComparisonData_({leftId:'E',rightId:'W'}),/Different utilities or units/);sandbox.getConsumptionIntelligence_=originalIntel;
