import { storage } from './storage.js';
import { initShell, toast, renderConnectionBanner, safeMessage } from './ui.js';
import { download } from './utils.js';
import { getApiConfig, saveApiConfig } from './api-config.js';
import { dataAdapter } from './data-adapter.js';
import { syncManager } from './sync-manager.js';

initShell();
const settingsForm=document.querySelector('#settingsForm');
if(settingsForm){const settings=storage.get().settings;Object.entries(settings).forEach(([key,value])=>{if(settingsForm.elements[key])settingsForm.elements[key].value=value??''});settingsForm.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries(new FormData(settingsForm));['defaultTariff','warningThreshold','criticalThreshold','evidenceWarningKb'].forEach(key=>values[key]=values[key]===''?null:Number(values[key]));storage.mutate(db=>Object.assign(db.settings,values));toast('Display preferences saved');setTimeout(()=>location.reload(),400)});document.querySelector('#export').onclick=()=>download('fm-energy-local-archive.json',storage.export());document.querySelector('#import').onchange=async event=>{try{storage.import(await event.target.files[0].text());toast('Local archive imported. It was not uploaded to Google Sheets.')}catch(error){toast('The selected local archive is invalid.')}};document.querySelector('#reset').onclick=()=>{if(confirm('Reset local preferences and drafts? Remote Google Sheet records will not be changed.')){storage.reset();location.reload()}};}
const apiForm=document.querySelector('#apiForm');
if(apiForm){const config=getApiConfig();apiForm.elements.baseUrl.value=config.developmentOverride?config.baseUrl:'';apiForm.elements.developmentOverride.checked=config.developmentOverride;apiForm.elements.mode.value=config.mode;apiForm.elements.apiToken.value=config.apiToken;const check=async()=>{const status=document.querySelector('#apiStatus');status.textContent='CHECKING…';try{const result=await dataAdapter.health();status.textContent=result.source==='live'?(getApiConfig().apiToken?'LIVE GOOGLE SHEET — WRITE ACCESS ENABLED':'LIVE GOOGLE SHEET — READ ONLY'):result.source==='mock'?'C7 TEST MODE':'CACHED — NOT CURRENT';renderConnectionBanner({source:result.source,lastSync:result.meta.timestamp||result.meta.cachedAt});toast('Google Sheet connection check passed')}catch(error){status.textContent=error.code==='API_NOT_CONFIGURED'?'SETUP REQUIRED':'CONNECTION ERROR';renderConnectionBanner({source:error.code==='API_NOT_CONFIGURED'?'unconfigured':'offline',message:safeMessage(error)});toast(safeMessage(error))}};apiForm.onsubmit=event=>{event.preventDefault();const values=Object.fromEntries(new FormData(apiForm));values.developmentOverride=apiForm.elements.developmentOverride.checked;saveApiConfig(values);toast('Google Sheet connection settings saved on this device');check()};document.querySelector('#healthCheck').onclick=check;document.querySelector('#clearWriteToken').onclick=()=>{const current=getApiConfig();saveApiConfig({...current,apiToken:''});apiForm.elements.apiToken.value='';document.querySelector('#apiStatus').textContent='LIVE GOOGLE SHEET — READ ONLY';toast('Saved write access removed. Read-only access remains available')};const legacy=syncManager.detectLegacyData(),panel=document.querySelector('#migrationPanel');if(legacy){panel.innerHTML=`<div class="migration-notice"><h3>Previous local records detected</h3><p>${legacy.likelyDemo?'The records appear to contain earlier local sample data.':''} They will not be merged or uploaded automatically. The recommended option is to archive them and use Google Sheets.</p><div class="case-actions"><button id="archiveLegacy" class="btn primary">Archive locally</button><button id="exportLegacy" class="btn">Export JSON</button></div></div>`;document.querySelector('#archiveLegacy').onclick=()=>{syncManager.archiveLegacy();toast('Previous local data archived; no remote records changed')};document.querySelector('#exportLegacy').onclick=()=>download('fm-energy-pre-m3-local-data.json',JSON.stringify(legacy.raw,null,2));}else panel.innerHTML='<p class="question-meta">No previous local official-data candidate was detected.</p>';}
