import { getApiConfig } from './api-config.js';
import { remoteStorage } from './remote-storage.js';
import { C7_MOCK, mockDashboard } from './mock-fixture.js';

const filter = (rows, params, map) => rows.filter(row => Object.entries(params || {}).every(([key, value]) => value === '' || value === undefined || String(row[map[key] || key]) === String(value)));
class MockStorage {
  async read(action, params = {}) {
    const routes = {
      health: () => ({ status: 'ok', spreadsheetAccess: false, spreadsheetTitle: 'Development C7 fixture', timezone: 'Asia/Dubai', apiVersion: 'v1', dataVersion: 'M2.0' }),
      getSettings: () => [], getDataQualityIssues: () => C7_MOCK.quality, getSites: () => filter(C7_MOCK.sites, params, { siteId: 'Site_ID', status: 'Status' }), getBuildings: () => C7_MOCK.buildings,
      getUtilities: () => C7_MOCK.utilities, getMeters: () => filter(C7_MOCK.meters, params, { meterId: 'Meter_ID', meterNumber: 'Meter_Number', siteId: 'Site_ID', utilityId: 'Utility_ID' }),
      getMeterReadings: () => C7_MOCK.readings, getConsumption: () => filter(C7_MOCK.consumption, params, { meterId: 'Meter_ID', siteId: 'Site_ID', utilityId: 'Utility_ID' }),
      getHistoricalConsumption: () => C7_MOCK.consumption, getAnomalies: () => C7_MOCK.anomalies, getCases: () => filter(C7_MOCK.cases, params, { caseId: 'Case_ID', meterId: 'Meter_ID', siteId: 'Site_ID' }),
      getEvidence: () => C7_MOCK.evidence, getCorrectiveActions: () => C7_MOCK.actions, getDashboard: mockDashboard,
      getPortfolioTree: () => ({ name: 'Portfolio', sites: C7_MOCK.sites.map(site => ({ site, buildings: [], unassignedMeters: C7_MOCK.meters.filter(meter => meter.Site_ID === site.Site_ID) })) }),
      getCaseDetails: () => ({ case: C7_MOCK.cases[0], meter: C7_MOCK.meters[0], site: C7_MOCK.sites[0], building: null, utility: C7_MOCK.utilities[0], investigationInputs: C7_MOCK.inputs, evidence: C7_MOCK.evidence, correctiveActions: C7_MOCK.actions, relatedAnomaly: C7_MOCK.anomalies[0], consumptionHistory: C7_MOCK.consumption }),
      getConsumptionIntelligence: () => ({items:[{record:C7_MOCK.consumption[1],currentConsumption:18615,comparisonValue:6640,difference:11975,percentageChange:180.346,historicalAverage:6640,historicalMinimum:6640,historicalMaximum:6640,normalRange:{minimum:null,maximum:null},dailyNormalized:null,dataQualityStatus:'Pending verification',anomalyStatus:'Data issue',classification:'Data issue',explanation:'C7 is 180% above June, but meter readings and configuration must be verified before deciding why.',comparisonBasis:'Previous month',actionRecommended:'Collect and verify June and July readings, dates, photographs, CT ratio and multiplier.',investigationRecommended:true,unit:'kWh',period:'2026-07'}],highest:[{record:C7_MOCK.consumption[1],currentConsumption:18615,comparisonValue:6640,difference:11975,percentageChange:180.346,historicalAverage:6640,historicalMinimum:6640,historicalMaximum:6640,normalRange:{minimum:null,maximum:null},dailyNormalized:null,dataQualityStatus:'Pending verification',anomalyStatus:'Data issue',classification:'Data issue',explanation:'C7 is 180% above June, but meter readings and configuration must be verified before deciding why.',comparisonBasis:'Previous month',actionRecommended:'Collect and verify June and July readings, dates, photographs, CT ratio and multiplier.',investigationRecommended:true,unit:'kWh',period:'2026-07'}],lowest:[],largestIncrease:[{record:C7_MOCK.consumption[1],currentConsumption:18615,comparisonValue:6640,difference:11975,percentageChange:180.346,historicalAverage:6640,historicalMinimum:6640,historicalMaximum:6640,normalRange:{minimum:null,maximum:null},dailyNormalized:null,dataQualityStatus:'Pending verification',anomalyStatus:'Data issue',classification:'Data issue',explanation:'C7 is 180% above June, but meter readings and configuration must be verified before deciding why.',comparisonBasis:'Previous month',actionRecommended:'Collect and verify June and July readings, dates, photographs, CT ratio and multiplier.',investigationRecommended:true,unit:'kWh',period:'2026-07'}],largestReduction:[],outsideNormalRange:[],missingOrSuspicious:[{record:C7_MOCK.consumption[1],currentConsumption:18615,comparisonValue:6640,difference:11975,percentageChange:180.346,historicalAverage:6640,historicalMinimum:6640,historicalMaximum:6640,normalRange:{minimum:null,maximum:null},dailyNormalized:null,dataQualityStatus:'Pending verification',anomalyStatus:'Data issue',classification:'Data issue',explanation:'C7 is 180% above June, but meter readings and configuration must be verified before deciding why.',comparisonBasis:'Previous month',actionRecommended:'Collect and verify June and July readings, dates, photographs, CT ratio and multiplier.',investigationRecommended:true,unit:'kWh',period:'2026-07'}],meta:{total:1,page:1,pageSize:50}}),
      getHistoricalAnalysis: () => [{group:'Electricity|kWh',utility:'Electricity',unit:'kWh',series:C7_MOCK.consumption.map(x=>({period:x.Period,value:x.Consumption,rolling3:null,dataQualityStatus:x.Data_Quality_Status})),annualTotals:{2026:25255},historicalAverage:12627.5,historicalMinimum:6640,historicalMaximum:18615,dataGaps:2}],
      getComparisonData: () => ({items:[{actualValue:18615,difference:11975,percentageChange:180.346,rank:1,historicalContext:'C7 requires data verification before a valid operational conclusion.',dataQualityStatus:'Pending verification',comparisonValid:true,unit:'kWh',record:C7_MOCK.consumption[1]}],notes:'Comparisons are valid only within the same utility and unit.'}),
      getOpportunities: () => [{type:'Missing tariff',classification:'More data required',record:C7_MOCK.consumption[1],explanation:'Cost impact unavailable — tariff not entered',costImpact:null,actionRecommended:'Enter an approved tariff when available.'}],
      getTodaySummary: () => ({utilitySummary:[{name:'Electricity',currentConsumption:18615,previousPeriodChange:180.346,sameMonthLastYearChange:null,status:'Review',explanation:'C7 increased sharply, but source readings remain awaiting verification.'}],priorities:[{site:'Etihad Plaza',utility:'Electricity',problem:'Verify C7 readings',reason:'July is 11,975 kWh above June and source readings are not verified.',priority:'Critical',actionRecommended:'Collect and verify readings, dates, photographs, CT ratio and multiplier.',caseId:'CASE-2026-0001'}],high:[{record:C7_MOCK.consumption[1],currentConsumption:18615,comparisonValue:6640,difference:11975,percentageChange:180.346,historicalAverage:6640,historicalMinimum:6640,historicalMaximum:6640,normalRange:{minimum:null,maximum:null},dailyNormalized:null,dataQualityStatus:'Pending verification',anomalyStatus:'Data issue',classification:'Data issue',explanation:'C7 is 180% above June, but meter readings and configuration must be verified before deciding why.',comparisonBasis:'Previous month',actionRecommended:'Collect and verify June and July readings, dates, photographs, CT ratio and multiplier.',investigationRecommended:true,unit:'kWh',period:'2026-07'}],low:[],verifiedImprovements:[],dataQuality:{missingReadings:0,negativeValues:0,duplicateReadings:0,unverifiedReadings:0,suspiciousZeros:0,brokenContinuity:0},today:{newAlerts:1,overdueChecks:0,awaitingVerification:0,awaitingClient:0,awaitingEngineer:0,awaitingContractor:0,casesReadyToClose:0}}),
      getMonthlyChecklist: () => ({items:['Enter or import month-end readings','Verify readings','Resolve missing data','Review current month versus previous month','Review same month last year','Review historical outliers','Open investigations only where justified','Review utility costs','Verify savings','Generate monthly report'].map((label,index)=>({step:index+1,label,status:'Not checked'}))})
    };
    if (!routes[action]) throw new Error(`Mock action is not implemented: ${action}`);
    return { data: routes[action](), source: 'mock', meta: { apiVersion: 'v1', timestamp: new Date().toISOString() } };
  }
  async write() { throw new Error('Mock mode is read-only. Switch to remote mode for controlled writes.'); }
}

export class DataAdapter {
  constructor(configProvider = getApiConfig, remote = remoteStorage, mock = new MockStorage()) { this.configProvider = configProvider; this.remote = remote; this.mock = mock; }
  provider() { return this.configProvider().mode === 'mock' ? this.mock : this.remote; }
  read(action, params) { return this.provider().read(action, params); }
  write(action, body) { return this.provider().write(action, body); }
  health() { return this.read('health'); }
  getSettings() { return this.read('getSettings'); } getSites(p={}) { return this.read('getSites', p); } getBuildings(p={}) { return this.read('getBuildings', p); } getUtilities(p={}) { return this.read('getUtilities', p); } getMeters(p={}) { return this.read('getMeters', p); }
  getMeterReadings(p={}) { return this.read('getMeterReadings', p); } getConsumption(p={}) { return this.read('getConsumption', p); } getHistoricalConsumption(p={}) { return this.read('getHistoricalConsumption', p); } getAnomalies(p={}) { return this.read('getAnomalies', p); }
  getConsumptionIntelligence(p={}) { return this.read('getConsumptionIntelligence', p); } getHistoricalAnalysis(p={}) { return this.read('getHistoricalAnalysis', p); } getComparisonData(p={}) { return this.read('getComparisonData', p); } getOpportunities(p={}) { return this.read('getOpportunities', p); } getTodaySummary(p={}) { return this.read('getTodaySummary', p); } getMonthlyChecklist() { return this.read('getMonthlyChecklist'); } getCases(p={}) { return this.read('getCases', p); } getCaseDetails(caseId) { return this.read('getCaseDetails', { caseId }); } getEvidence(p={}) { return this.read('getEvidence', p); } getCorrectiveActions(p={}) { return this.read('getCorrectiveActions', p); } getDashboard(p={}) { return this.read('getDashboard', p); } getPortfolioTree() { return this.read('getPortfolioTree'); }
  createMeterReading(body) { return this.write('createMeterReading', body); } updateMeterReading(body) { return this.write('updateMeterReading', body); } createInvestigationInput(body) { return this.write('createInvestigationInput', body); } updateInvestigationInput(body) { return this.write('updateInvestigationInput', body); }
  createEvidence(body) { return this.write('createEvidence', body); } updateEvidenceStatus(body) { return this.write('updateEvidenceStatus', body); } createCorrectiveAction(body) { return this.write('createCorrectiveAction', body); } updateCorrectiveAction(body) { return this.write('updateCorrectiveAction', body); } updateCase(body) { return this.write('updateCase', body); } confirmRootCause(body) { return this.write('confirmRootCause', body); } closeCase(body) { return this.write('closeCase', body); } updateAnomaly(body) { return this.write('updateAnomaly', body); } createInvestigationCase(body) { return this.write('createInvestigationCase', body); }
}
export const dataAdapter = new DataAdapter();
