import { dataAdapter } from './data-adapter.js';
import { initShell, toast, renderConnectionBanner, safeMessage } from './ui.js';
import { displayValue } from './schema-mapping.js';
import { esc, date } from './utils.js';
import { storage } from './storage.js';
initShell();
const caseId=new URLSearchParams(location.search).get('caseId')||'CASE-2026-0001';
const form=document.querySelector('#dropForm'),fileInput=document.querySelector('#evidenceFile');let evidence=[],questions=[];
const types=['Meter photograph','Meter reading','Clamp-meter measurement','Power-analyser record','Thermal image','BMS screenshot','DB schedule','Single-line diagram','Work order','Permit','Technician report','Comment','Other document'];form.elements.type.innerHTML=types.map(type=>`<option>${type}</option>`).join('');
async function load(){try{const [items,details]=await Promise.all([dataAdapter.getEvidence({caseId}),dataAdapter.getCaseDetails(caseId)]);evidence=items.data;questions=details.data.investigationInputs||[];form.elements.questionId.innerHTML='<option value="">General case evidence</option>'+questions.map(q=>`<option value="${esc(q.Question_ID)}">${esc(q.Question_ID)} · ${esc(displayValue(q.Question))}</option>`).join('');renderConnectionBanner({source:items.source,lastSync:items.meta.timestamp||items.meta.cachedAt});render()}catch(error){renderConnectionBanner({source:error.code==='API_NOT_CONFIGURED'?'unconfigured':'offline',message:safeMessage(error)});document.querySelector('#evidenceGallery').innerHTML=`<div class="empty-state"><h3>Evidence unavailable</h3><p>${safeMessage(error)}</p></div>`}}
function render(){const verified=evidence.filter(item=>item.Verification_Status==='Verified').length;document.querySelector('#evidenceSummary').innerHTML=`<span><b>${evidence.length}</b><small>Total items</small></span><span><b>${verified}</b><small>Verified</small></span><span><b>${evidence.length-verified}</b><small>Awaiting review</small></span>`;const filter=document.querySelector('#evidenceFilter').value,items=evidence.filter(item=>!filter||item.Evidence_Type===filter);document.querySelector('#evidenceGallery').innerHTML=items.length?items.slice().reverse().map(item=>`<article class="evidence-tile"><div class="file-placeholder">▧</div><div><span class="badge">${esc(displayValue(item.Evidence_Type))}</span><h3><a href="${esc(item.File_Link||'#')}" target="_blank" rel="noopener">${esc(displayValue(item.File_Name))}</a></h3><p>${esc(displayValue(item.Remarks))}</p><dl><div><dt>Date</dt><dd>${item.Uploaded_At?date(item.Uploaded_At):'Not provided'}</dd></div><div><dt>Uploaded by</dt><dd>${esc(displayValue(item.Uploaded_By))}</dd></div><div><dt>Related question</dt><dd>${esc(displayValue(item.Question_ID))}</dd></div><div><dt>Verification</dt><dd><select class="verify-evidence" data-id="${esc(item.Evidence_ID)}">${['Pending verification','Verified','Needs recheck','Rejected'].map(status=>`<option ${status===item.Verification_Status?'selected':''}>${status}</option>`).join('')}</select></dd></div></dl></div></article>`).join(''):'<div class="empty-state"><h3>No matching evidence</h3><p>The live Evidence_Register returned no matching records.</p></div>';document.querySelectorAll('.verify-evidence').forEach(select=>select.onchange=async()=>{if(!confirm('Update this evidence verification status in the live Google Sheet?'))return load();try{await dataAdapter.updateEvidenceStatus({evidenceId:select.dataset.id,verificationStatus:select.value,updatedBy:storage.get().settings.userName||'Not provided'});toast('Evidence status updated and audited');load()}catch(error){toast(safeMessage(error));load()}})}
document.querySelector('#chooseFile').onclick=()=>fileInput.click();fileInput.onchange=()=>{const file=fileInput.files[0];document.querySelector('#fileState').textContent=file?`${file.name} selected — upload it to approved storage and paste its HTTPS link. Binary upload is not enabled.`:'No file selected';if(file&&!form.elements.title.value)form.elements.title.value=file.name};const drop=document.querySelector('#dropZone');['dragenter','dragover'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove('dragging')}));drop.ondrop=event=>{fileInput.files=event.dataTransfer.files;fileInput.onchange()};document.querySelector('#evidenceFilter').onchange=render;form.onsubmit=async event=>{event.preventDefault();if(!confirm('Create this evidence metadata record in the live Google Sheet?'))return;try{await dataAdapter.createEvidence({caseId,questionId:form.elements.questionId.value,fileLink:form.elements.fileLink.value,fileName:form.elements.title.value,uploader:storage.get().settings.userName||'Not provided',evidenceType:form.elements.type.value,verificationStatus:form.elements.verificationStatus.value,remarks:form.elements.notes.value});form.reset();toast('Evidence metadata created and audited');load()}catch(error){toast(safeMessage(error))}};load();
