import { dataAdapter } from './data-adapter.js';
import { initShell, toast, renderConnectionBanner, safeMessage } from './ui.js';
import { offlineDraftStore } from './offline-draft-store.js';
import { storage } from './storage.js';
import { displayValue } from './schema-mapping.js';
initShell();
const caseId=new URLSearchParams(location.search).get('caseId')||'CASE-2026-0001';let details=null;
async function load(){try{const result=await dataAdapter.getCaseDetails(caseId);details=result.data;renderConnectionBanner({source:result.source,lastSync:result.meta.timestamp||result.meta.cachedAt});const item=details.case;document.querySelector('#fieldTask').innerHTML=`<article class="field-task"><span class="task-icon">✓</span><div><span class="badge critical">${displayValue(item.Case_ID)} · ${displayValue(item.Severity)}</span><h1>${displayValue(item.Next_Required_Action||'Collect and verify meter readings and evidence')}</h1><p>${displayValue(item.Case_Title)}</p><small>Assigned role · ${displayValue(item.Assigned_To)}</small></div></article>`}catch(error){renderConnectionBanner({source:error.code==='API_NOT_CONFIGURED'?'unconfigured':'offline',message:safeMessage(error)});document.querySelector('#fieldTask').innerHTML='<article class="field-task"><div><h1>Offline field draft</h1><p>Record the task locally. It will not be submitted automatically.</p></div></article>'}}
const recordedAt=document.querySelector('[name=recordedAt]');recordedAt.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
document.querySelector('#fieldForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));const photo=form.elements.photo.files[0];const body={caseId,questionId:'',answer:`Reading: ${values.reading||'Not provided'}; Current: ${values.current||'Not provided'} A; Voltage: ${values.voltage||'Not provided'} V`,technicalNotes:values.remarks||'',status:'Answered',enteredBy:storage.get().settings.userName||'Not provided'};const draft=offlineDraftStore.save({action:'createInvestigationInput',body,photoMetadata:photo?{name:photo.name,size:photo.size,type:photo.type}:null,recordedAt:values.recordedAt});toast('Field update saved as a local draft. It was not submitted automatically.');if(navigator.onLine&&confirm('The draft is saved. Submit it once to the live Google Sheet now?')){try{await dataAdapter.createInvestigationInput(body);offlineDraftStore.remove(draft.draftId);toast('Field update submitted and audited')}catch(error){toast(`${safeMessage(error)} Draft retained locally.`)}}form.reset();recordedAt.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)};load();
