import { dataAdapter } from './data-adapter.js';
import { initShell, renderConnectionBanner, safeMessage, toast } from './ui.js';
import { displayValue } from './schema-mapping.js';
import { esc, date } from './utils.js';
initShell();
let meters=[],sites=[],utilities=[];
const body=document.querySelector('#metersBody');
const val=value=>esc(displayValue(value));
async function setup(){try{const results=await Promise.all([dataAdapter.getMeters(),dataAdapter.getSites(),dataAdapter.getUtilities()]);meters=results[0].data;sites=results[1].data;utilities=results[2].data;document.querySelector('#meterSource').textContent=results[0].source==='live'?'LIVE GOOGLE SHEET':results[0].source.toUpperCase();renderConnectionBanner({source:results[0].source,lastSync:results[0].meta.timestamp||results[0].meta.cachedAt});document.querySelector('#meterSite').innerHTML='<option value="">All sites</option>'+sites.map(x=>`<option value="${esc(x.Site_ID)}">${val(x.Site_Name)}</option>`).join('');document.querySelector('#meterUtility').innerHTML='<option value="">All utilities</option>'+utilities.map(x=>`<option value="${esc(x.Utility_ID)}">${val(x.Utility_Name)}</option>`).join('');render();const requested=new URLSearchParams(location.search).get('meterId');if(requested)openMeter(requested)}catch(error){renderConnectionBanner({source:error.code==='API_NOT_CONFIGURED'?'unconfigured':'offline',message:safeMessage(error)});body.innerHTML=`<tr><td colspan="7"><div class="empty-state"><h3>Live meters unavailable</h3><p>${safeMessage(error)}</p></div></td></tr>`}}
function render(){const query=document.querySelector('#meterSearch').value.toLowerCase(),site=document.querySelector('#meterSite').value,utility=document.querySelector('#meterUtility').value,status=document.querySelector('#meterStatus').value;const rows=meters.filter(m=>(!query||JSON.stringify(m).toLowerCase().includes(query))&&(!site||m.Site_ID===site)&&(!utility||m.Utility_ID===utility)&&(!status||m.Status===status));body.innerHTML=rows.length?rows.map(m=>`<tr><td><b>${val(m.Meter_Name)}</b><small>${val(m.Meter_Number)}</small></td><td>${val(sites.find(s=>s.Site_ID===m.Site_ID)?.Site_Name)}<small>${val(m.Building_Name)}</small></td><td>${val(utilities.find(u=>u.Utility_ID===m.Utility_ID)?.Utility_Name)}<small>${val(m.Unit)}</small></td><td>${val(m.Meter_Level)}<small>Parent: ${val(m.Parent_Meter_ID)}</small></td><td>${val(m.CT_Ratio)}<small>Multiplier: ${val(m.Multiplier)}</small></td><td><span class="badge">${val(m.Status)}</span><small>${val(m.Data_Status)}</small></td><td><button class="btn small view-meter" data-id="${esc(m.Meter_ID)}">View</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty-state">No matching live meters.</div></td></tr>';document.querySelectorAll('.view-meter').forEach(button=>button.onclick=()=>openMeter(button.dataset.id))}
async function openMeter(id){const meter=meters.find(item=>item.Meter_ID===id);if(!meter)return;const detail=document.querySelector('#meterDetail');detail.innerHTML='<div class="skeleton-row"></div><div class="skeleton-row"></div>';try{const [readings,consumption,anomalies,cases]=await Promise.all([dataAdapter.getMeterReadings({meterId:id}),dataAdapter.getConsumption({meterId:id}),dataAdapter.getAnomalies({meterId:id}),dataAdapter.getCases({meterId:id})]);const latest=[...readings.data].sort((a,b)=>new Date(b.Reading_Date)-new Date(a.Reading_Date))[0];detail.innerHTML=`<div class="card-title"><div><span class="eyebrow">${val(meter.Meter_ID)}</span><h2>${val(meter.Meter_Name)}</h2></div><button id="addReading" class="btn primary small">+ Reading</button></div><dl class="detail-grid">${[['Meter number',meter.Meter_Number],['Site',sites.find(s=>s.Site_ID===meter.Site_ID)?.Site_Name],['Building',meter.Building_Name],['Utility',utilities.find(u=>u.Utility_ID===meter.Utility_ID)?.Utility_Name],['Unit',meter.Unit],['Meter level',meter.Meter_Level],['Parent meter',meter.Parent_Meter_ID],['CT ratio',meter.CT_Ratio],['Multiplier',meter.Multiplier],['Frequency',meter.Reading_Frequency],['Data status',meter.Data_Status],['Latest reading',latest?.Reading_Value],['Latest date',latest?.Reading_Date?date(latest.Reading_Date):null],['Verification',latest?.Verification_Status]].map(([k,v])=>`<div><dt>${k}</dt><dd>${val(v)}</dd></div>`).join('')}</dl><h3>Monthly consumption trend</h3><canvas id="meterMonthly"></canvas><h3>Daily reading trend</h3><canvas id="meterDaily"></canvas><div class="grid two"><div><h3>Related anomalies</h3><b>${anomalies.data.length}</b></div><div><h3>Related cases</h3><b>${cases.data.length}</b></div></div>`;document.querySelector('#addReading').onclick=()=>{const form=document.querySelector('#readingForm');form.elements.meterId.value=id;form.elements.enteredBy.value='';document.querySelector('#readingDialog').showModal()};if(window.Chart){new Chart(document.querySelector('#meterMonthly'),{type:'line',data:{labels:consumption.data.map(x=>displayValue(x.Period||x.Period_From)),datasets:[{label:meter.Unit||'Recorded unit',data:consumption.data.map(x=>x.Consumption??x.Consumption_Value),borderColor:'#176b87'}]}});new Chart(document.querySelector('#meterDaily'),{type:'line',data:{labels:readings.data.map(x=>displayValue(x.Reading_Date)),datasets:[{label:'Meter reading',data:readings.data.map(x=>x.Reading_Value),borderColor:'#7755d9'}]}})}}catch(error){detail.innerHTML=`<div class="empty-state"><p>${safeMessage(error)}</p></div>`}}
const form=document.querySelector('#readingForm');form.onsubmit=async event=>{event.preventDefault();if(event.submitter?.value==='cancel')return document.querySelector('#readingDialog').close();if(!confirm('Submit this reading once to the live Google Sheet? Duplicate writes are not retried automatically.'))return;try{const values=Object.fromEntries(new FormData(form));values.readingValue=Number(values.readingValue);await dataAdapter.createMeterReading(values);document.querySelector('#readingDialog').close();toast('Meter reading created and audited');setup()}catch(error){toast(safeMessage(error))}};
document.querySelectorAll('#meterSearch,#meterSite,#meterUtility,#meterStatus').forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',render));setup();
