import { dataAdapter } from './data-adapter.js';
import { initShell, renderConnectionBanner, safeMessage } from './ui.js';
import { displayValue } from './schema-mapping.js';
import { esc } from './utils.js';
initShell();
let tree=null;
const element=document.querySelector('#portfolioTree');
function meterHtml(meter){return `<li><a href="meters.html?meterId=${encodeURIComponent(meter.Meter_ID)}"><span>▤</span><b>${esc(displayValue(meter.Meter_Name))}</b><small>${esc(displayValue(meter.Meter_Number))} · ${esc(displayValue(meter.Status))}</small></a></li>`;}
function render(){const query=document.querySelector('#portfolioSearch').value.toLowerCase(),status=document.querySelector('#portfolioStatus').value;if(!tree)return;element.innerHTML=tree.sites?.length?tree.sites.map(siteNode=>{const site=siteNode.site;if(query&&!JSON.stringify(siteNode).toLowerCase().includes(query))return'';const buildings=(siteNode.buildings||[]).filter(node=>!status||node.building.Status===status);return `<details open class="portfolio-node site-node"><summary><span>⌂</span><b>${esc(displayValue(site.Site_Name))}</b><small>${esc(displayValue(site.Status))}</small></summary><div>${buildings.map(buildingNode=>`<details class="portfolio-node"><summary><span>▦</span><b>${esc(displayValue(buildingNode.building.Building_Name))}</b></summary>${(buildingNode.utilities||[]).map(utilityNode=>`<section class="utility-node"><h3>${esc(displayValue(utilityNode.utility.Utility_Name))}</h3><ul>${(utilityNode.meters||[]).map(meterHtml).join('')}</ul></section>`).join('')}</details>`).join('')}${siteNode.unassignedMeters?.length?`<section class="utility-node"><h3>Building pending verification</h3><ul>${siteNode.unassignedMeters.map(meterHtml).join('')}</ul></section>`:''}</div></details>`}).join(''):'<div class="empty-state"><h3>No portfolio records</h3><p>The live API returned no matching sites.</p></div>';}
async function load(){element.innerHTML='<div class="skeleton-row"></div><div class="skeleton-row"></div>';try{const result=await dataAdapter.getPortfolioTree();tree=result.data;document.querySelector('#portfolioBadge').textContent=result.source==='live'?'LIVE GOOGLE SHEET':result.source.toUpperCase();renderConnectionBanner({source:result.source,lastSync:result.meta.timestamp||result.meta.cachedAt});render()}catch(error){renderConnectionBanner({source:error.code==='API_NOT_CONFIGURED'?'unconfigured':'offline',message:safeMessage(error)});element.innerHTML=`<div class="empty-state"><h3>Portfolio unavailable</h3><p>${safeMessage(error)}</p></div>`}}
document.querySelector('#portfolioSearch').oninput=render;document.querySelector('#portfolioStatus').onchange=render;document.querySelector('#portfolioRetry').onclick=load;load();
