const tasks=[
{ids:['Q3','Q4','Q5','Q7','Q9','Q20','Q21'],title:'Upload or record the June and July C7 meter readings, meter photographs, exact reading dates, and CT ratio.',why:'Basic source data must be validated before advanced testing.',person:'Meter reader / Facility Engineer',tool:'Meter register and camera',evidence:'June and July readings, dated photos, CT plate and multiplier',priority:'Critical',safety:'Do not open energized panels without authorization.'},
{ids:['Q8','Q32','Q33'],title:'Validate the exact June and July reading periods.',why:'Normalization can determine whether the increase is caused by an extended billing period.',person:'Energy Analyst',tool:'Reading log',evidence:'Timestamped reading register',priority:'High',safety:'No electrical access is required.'},
{ids:['Q22','Q24','Q26','Q29'],title:'Confirm meter configuration and health.',why:'A configuration or meter issue must be excluded before load tracing.',person:'Authorized Electrical Engineer',tool:'Meter manual and calibrated analyser',evidence:'CT inspection and kW comparison record',priority:'High',safety:'Electrical testing must be performed by competent authorized personnel using suitable PPE.'},
{ids:['Q40','Q41','Q51','Q52'],title:'Map connected loads and check new or temporary supplies.',why:'A verified load inventory focuses subsequent measurement.',person:'Electrical Supervisor',tool:'SLD and DB schedule',evidence:'Signed feeder schedule and site photographs',priority:'High',safety:'Do not isolate critical loads without operational approval.'},
{ids:['Q76','Q77','Q79','Q81'],title:'Measure daytime, night-time and feeder demand.',why:'Demand profiles identify continuous or abnormal feeders.',person:'Authorized Electrical Engineer',tool:'Calibrated power analyser / clamp meter',evidence:'Timestamped analyser record',priority:'High',safety:'Follow permit-to-work and lockout/tagout procedures.'},
{ids:['Q96','Q97'],title:'Confirm and document the evidence-supported root cause.',why:'Corrective work requires a defensible causal finding.',person:'Facility Manager',tool:'Evidence register',evidence:'Approved root-cause statement with linked evidence',priority:'High',safety:'Do not depend only on software conclusions for electrical safety decisions.'},
{ids:['Q100','Q101','Q102'],title:'Assign the corrective action and target date.',why:'A confirmed finding must be converted into controlled work.',person:'Facility Manager',tool:'Work order',evidence:'Approved action record',priority:'Medium',safety:'Obtain shutdown and client approval where required.'},
{ids:['Q110','Q114','Q115'],title:'Verify post-correction consumption.',why:'Closure requires proof that consumption returned to normal.',person:'Energy Manager',tool:'Meter trend and analyser',evidence:'Post-action readings and saving calculation',priority:'High',safety:'Use the approved measurement procedure.'}];
export function recommend(c){return tasks.find(t=>t.ids.some(id=>!['Answered','Verified','Not applicable'].includes(c.questions.find(q=>q.id===id)?.status)))||{title:'Complete controlled case closure.',why:'All investigation and verification gates are complete.',person:'Facility Manager',tool:'Closure checklist',evidence:'Approved final report',priority:'Medium',safety:'Confirm operational approval before closure.'}}
