import { storage } from './storage.js';
import { getApiConfig, isApiConfigured } from './api-config.js';

export function toast(message) { const element=document.querySelector('#toast');if(!element)return;element.textContent=message;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),2600); }
export function initShell() { storage.init(); const page=document.body.dataset.page; document.querySelectorAll(`[data-page="${page}"]`).forEach(item=>item.classList.add('active')); const settings=storage.get().settings; const system=matchMedia('(prefers-color-scheme:dark)').matches; document.documentElement.dataset.theme=settings.theme==='system'?(system?'dark':'light'):settings.theme; document.querySelector('#theme')?.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';storage.mutate(db=>db.settings.theme=dark?'dark':'light')}); document.querySelector('#menu')?.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open')); const help={dashboard:'This page summarizes current utility performance and what needs your attention today.',consumption:'This page shows where utility use is high, low, normal or abnormal.',alerts:'This page lists readings and consumption values that require review.',case:'This page guides you step by step to confirm the cause and corrective action.','data-entry':'This page is used to enter readings and review meter master information.',reports:'This page creates clear operational reports from verified records.',settings:'This page manages your Google Sheet connection and display preferences.',portfolio:'This page lets you move from sites to buildings, utilities and meters.',analytics:'This page explains historical patterns from available records.',evidence:'This page keeps the documents and links supporting investigations.',field:'This page gives technicians a simple way to record today’s assigned check.'};const top=document.querySelector('.topbar>div:first-child');if(top&&help[page]&&!top.querySelector('.page-help'))top.insertAdjacentHTML('beforeend',pageHelp(help[page]));if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{}); }
export function renderConnectionBanner({ source='loading', lastSync=null, message='' }={}) { let banner=document.querySelector('#connectionBanner');if(!banner){banner=document.createElement('section');banner.id='connectionBanner';banner.className='connection-banner';document.querySelector('main .topbar')?.after(banner);}const config=getApiConfig();const labels={live:'LIVE GOOGLE SHEET',cache:'CACHED — NOT CURRENT',mock:'MOCK MODE · REAL C7 FIXTURE',loading:'CONNECTING…',offline:'OFFLINE / CONNECTION ERROR',unconfigured:'API SETUP REQUIRED'};banner.dataset.state=source;banner.innerHTML=`<div><b>${labels[source]||labels.offline}</b><span>${message||((source==='unconfigured'||(!isApiConfigured(config)&&source!=='mock'))?'Configure the Apps Script deployment URL in Settings.':lastSync?`Last successful sync: ${new Date(lastSync).toLocaleString()}`:'')}</span></div>${['offline','unconfigured'].includes(source)?`<button class="btn small" data-retry>${source==='unconfigured'?'Open Settings':'Retry'}</button>`:''}`;banner.querySelector('[data-retry]')?.addEventListener('click',()=>source==='unconfigured'?location.href='settings.html#api':location.reload());return banner; }
export function safeMessage(error){if(error?.code==='PERMISSION_DENIED')return'Permission denied. Verify the API token and deployment access.';if(error?.code==='API_NOT_CONFIGURED')return'Configure the Google Apps Script URL in Settings.';if(error?.code==='CONNECTION_ERROR')return'The live Google Sheet backend is unavailable. Cached reads may be shown.';return'The requested data could not be loaded.';}

export const STATUS_SYSTEM = Object.freeze({
  success: ['normal','verified','completed','closed'],
  review: ['review','review required','watch'],
  priority: ['high','high priority','abnormal'],
  critical: ['critical','data issue'],
  progress: ['in progress','data collection','under investigation'],
  neutral: ['missing data','not enough information','not assessed','pending verification','not available','not provided']
});
export function statusTone(status='') { const value=String(status).toLowerCase();return Object.entries(STATUS_SYSTEM).find(([,terms])=>terms.some(term=>value.includes(term)))?.[0]||'neutral'; }
export function statusBadge(status,label=status) { const tone=statusTone(status);return `<span class="status-pill status-${tone}"><span class="status-dot" aria-hidden="true"></span>${label}</span>`; }
export function emptyState(title,message,actionHtml='') { return `<div class="empty-state"><span aria-hidden="true">◌</span><h3>${title}</h3><p>${message}</p>${actionHtml}</div>`; }
export function pageHelp(text) { return `<details class="page-help"><summary>What is this page?</summary><p>${text}</p></details>`; }
